### PR TITLE
Improved settings page, switched from using env variables to settings

### LINKED ISSUE #133: FRP: Integrate the template settings page
### What is your proposal 🚀
We need to add a settings page (like web.ycorpo.com/settings), the one available in the template repo, to be able to overwrite some stuff, and mostly yDaemon Uri in case something is down!

The [`useSettings.tsx`](https://github.com/yearn/web-lib/blob/main/packages/web-lib/contexts/useSettings.tsx) exposes a bunch of functions to be able to overwrite the defaults settings used by the app.
Every app should use `useSettings` variables instead of local constants, variables or env.

For ex, the [`YDAEMON_BASE_URL`](https://github.com/yearn/yearn-watch/blob/main/next.config.js#L47) env variable should ne be used, but the [`yDaemonBaseURI`](https://github.com/yearn/web-lib/blob/4638bbd2a555059c74af9d23aafeeb6b7e5d31f7/packages/web-lib/contexts/useSettings.tsx#L11) should be used instead

### What does this solve ? 🛠
Provide a better **DE**fi and way to overwrite settings if our stuff are down

### More 🔎
Linked to #132

### PR DESCRIPTION
**Pull request by ai-slave**
Fixes #133

### CODE REVIEW

**Comment by ai-slave** [comment]
@Majorfi just not sure if Subgraph settings are needed here

**Comment by Majorfi** [comment]
From memories, they are not

**Comment by Majorfi** [comment]
Hey @ai-slave !
Thank you for your PR! 
Could you fix the [build errors](https://github.com/yearn/yearn-watch/actions/runs/3536543114/jobs/5940537300)?

**Comment by ai-slave** [comment]
Should be good now

**Review by Majorfi — DISMISSED** [review]

**Review by Majorfi — APPROVED** [review]

**Pull request merged**
