### PR TITLE
Add sortable feature on track page.

### LINKED ISSUE #115: FRP: On `track Keep CRV` page make all columns sort-able
### What is your proposal 🚀
Make all columns sort-able not just the first and second one. This is so you can easily see which has the highest keepcrv %

image

### What does this solve ? 🛠
Easier to see the data

### More 🔎
*N/A*

### PR DESCRIPTION
**Pull request by CutupAngel**

### CODE REVIEW

**Comment by CutupAngel** [comment]
PR for [115](https://github.com/yearn/yearn-watch/issues/115)

**Comment by CutupAngel** [comment]
Please review this; @Majorfi

**Review by Majorfi — APPROVED** [review]
LGTM, waiting for @DarkGhost7 approval too!

Nice work!

**Review by DarkGhost7 — APPROVED** [review]
Very nice LGTM! great job @CutupAngel

**Comment by DarkGhost7** [comment]
gtg @Majorfi

**Pull request merged**
